site_name: RTD Playground
theme:
    name: readthedocs
docs_dir: docs
pages:
  - 'index.md'
  - 'zedeid-did-siop-lib.md'
  - 'zedeid-vcsd-lib.md'
  - 'zedeid-hdk-wallet.md'      
  - 'markdown-cheat-sheet.md'
